### ISSUE TITLE
Django 3.0 support

### ISSUE THREAD

**Issue by Nadock** [joostrijneveld/django-embed-template#12]
Any plans to add support for Django 3.0?

And/or is this project even still being supported? There hasn’t been activity since 2017.

**Comment by joostrijneveld** [comment]
I've not been involved in any Django projects lately, so development of this tool hasn't had any priority.. I have no idea how much effort it would be to update to Django 3.0 (and do not currently plan to spend significant time on this), but would very much welcome pull requests in that direction.

**Comment by Nadock** [comment]
Hi @joostrijneveld, apologies about the delayed response, life's been busy. I've opened a PR as you suggested, let me know what you think.

**Comment by joostrijneveld** [comment]
Thanks! Happy to hear how it ends up working for you when you end up using it in Django 3 projects.
